### ISSUE TITLE
Remove 'Hey' and 'Firefox' from the dataset

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#102]
We should remove transcripts that are "Hey" and "Firefox" from the dataset.

**Comment by d33tah** [comment]
@ftyers could you elaborate this one?

**Comment by ftyers** [comment]
There was a "target segments" data drive for the numbers 0-9 and "Hey" and "Firefox" it was supposed to be for testing ASR trained on smaller datasets. I think the words "Hey" and "Firefox" won't be useful for language learning. You can grep the `validated.tsv` file for those strings and remove them.

**Comment by ftyers** [comment]
Blacklist implemented in 79c5172.
