### ISSUE TITLE
BiDi layout

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#22]
Make sure we have a layout that works for bidirectional text.

**Comment by d33tah** [comment]
@ftyers Actually, what needs to be done and why is it so urgent?

**Comment by ftyers** [comment]
There are a number of languages we support, like Arabic, Persian and Divehi, that are written right to left. It should be fairly easy to support. For example: https://stackoverflow.com/questions/28249466/arabic-html-layout-direction-with-css#28250228

**Comment by ftyers** [comment]
I've added a basic one:
![imatge](https://user-images.githubusercontent.com/449545/110057476-8d879880-7d58-11eb-92c3-01b63c1f8258.png)
vs.
![imatge](https://user-images.githubusercontent.com/449545/110057491-97110080-7d58-11eb-866c-93d2271d1cd6.png)

**Comment by ftyers** [comment]
Fixed in 48d04d1.
