### ISSUE TITLE
Add internationalization support

### ISSUE THREAD

**Issue by d33tah** [omnilingo/omnilingo#35]

**Comment by ftyers** [comment]
A good choice might be [Fluent](https://www.projectfluent.org/).

**Comment by d33tah** [comment]
Yup. The reason is that this way we'd already have translations of language names.

**Comment by ftyers** [comment]
I want to avoid Node.js or any massive JS frameworks, for the language names we could pull them in fairly easily, so it wouldn't be terrible for us to do it ourselves, but something light would be fine. I've asked on the Fluent matrix channel to see if it can be used with vanilla JS.

**Comment by ftyers** [comment]
* https://github.com/projectfluent/fluent.js/tree/master/fluent-dom
* https://github.com/projectfluent/fluent-web

**Comment by ftyers** [comment]
I've brute forced the language names, which I think should be enough for now. I'm going to close this, we can open it again when we need to translate something specific.
