### ISSUE TITLE
Implement edit distance using panphon

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#45]
This will require a g2p model per language.

https://github.com/dmort27/panphon

Potentially can use wikipron for that.

**Comment by d33tah** [comment]
This is super confusing. I'd need to see a demo first.

**Comment by ftyers** [comment]
> explanation (pasted from Matrix):

so panphon edit distance takes into account the phonetic value of different sounds
so e.g. "b" and "p" are closer together in terms of phonetic value than "b" and "z"
a good distractor for "bat" is "pat" but probably not "tat"
at the moment levenshtein distance would score (bat, pat) and (bat, tat) the same 
g2p = grapheme to phoneme, so going from e.g. "knight" -> /nait/ and "night" → /nait/

> how about when both insertion and a similar sound happens? say, boy => buoy

those have the same phonetic value
so are homophones
panphon would return 0 there, but we could combine the two metrics (levenshtein and panphon)
but it's an open question if "buoy" is a good distractor for "boy"
because the person would need to know the meaning of the sentence
or just go by frequency

**Comment by ftyers** [comment]
Implemented
