### ISSUE TITLE
Speed up question loading

### ISSUE THREAD

**Issue by d33tah** [omnilingo/omnilingo#48]
@ftyers said it's slow because of the code behind distractors. It would be a good idea to optimize that.

**Comment by ftyers** [comment]
This is the offending part:

```python

    # FIXME: This is really slow...
    sys.stderr.write("Generating distractors.\n")
    distractors = get_distractors(word_frequency)
    
    sys.stderr.write("Assigning distractors.\n")
    for question in questions:
        question["distractors"] = {}
        for token in question["tokenized"]:
            question["distractors"][token] = distractors[token]

    sys.stderr.write("Done.\n")
```

**Comment by d33tah** [comment]
@ftyers why are we creating distractors for each token?

**Comment by d33tah** [comment]
Actually, why are we copying references at all, instead of having this as a separate variable?

**Comment by ftyers** [comment]
Good question,
* We will need a (set of) distractor(s) for each token as we don't know which token will be gapped up front
* I wasn't able to work out a way to run two AJAX queries at the same time

**Comment by ftyers** [comment]
This is redundant now with the new backend.
