### ISSUE TITLE
Deleting a single language should only invalidate that language

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#51]
e.g. if we have hi/tr/fi, and we delete the cache for hi it should only regenerate that.

**Comment by d33tah** [comment]
Well, we could probably get rid of serializing `languages`. Sounds like a simple patch - instead of loading it from a file, build it on the list of matching files in the `cache`.

**Comment by ftyers** [comment]
Redundant with backend reimplementation.
