### ISSUE TITLE
Create an announcement board

### ISSUE THREAD

**Issue by d33tah** [omnilingo/omnilingo#68]
We'll want to be able to announce progress to our users and developers to keep them engaged. Signing up should be as simple as entering your e-mail and clicking "subscribe". Remember to set up SOME privacy policy.

**Comment by ftyers** [comment]
I'm wary about email lists... I very rarely get anything out of them and as you mention, they require a privacy policy. It might be better to advertise on places with easy follow/unfollow like diaspora/mastodon/twitter/etc.

I am not _against_ a list, I just think that it's better to start with avenues that don't require collecting email addresses/PII.

**Comment by d33tah** [comment]
In theory this something we can "outsource". Google Groups comes to head. I changed to "announcement board" though - our Matrix conversation got me thinking that maybe something like a Reddit community would be better.
