### ISSUE TITLE
Tokenisers multi issue

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#70]
Here is a list of languages that might require specific tokenisation for a first release:
- [x] **as**: specific punctuation characters, e.g. ।
- [x] **br**: apostrophes and hyphens
- [x] **ca**: apostrophes and hyphens
- [x] **cy**: apostrophes
- [x] **dv**: non-Latin script
- [x] **en**: apostrophes
- [x] **fa**: non-Latin script
- [x] **fr**: apostrophes 
- [x] **fy-NL**: apostrophes
- [x] **ga-IE**: apostrophes and hyphens
- [x] **hi**: non-Latin script
- **~~it~~**: apostrophes  #84 
- [x] **ja**: language without spaces 
- [x] **ka**: non-Latin script
- [x] **kab**: hyphens and apostrophes
- [x] **lg**: apostrophes
- [x] **mt**: hyphens
- [x] **or**: non-Latin script
- [x] **pa-IN**: non-Latin script
- [x] **pl**: ?
- [x] **pt**: hyphens 
- [x] **rm-sursilv**: apostrophes
- [x] **rm-vallader**: apostrophes
- [x] **ta**: non-Latin script
- [x] **th**: non-Latin script
- [x] **tr**: apostrophes
- [x] **uk**: apostrophes
- [x] **zh-CN**: language without spaces 
- [x] **zh-HK**: language without spaces 
- [x] **zh-TW**: language without spaces 

Click when checked and implemented. Each tokeniser should have a test set.

**Comment by d33tah** [comment]
...better, but I'd still split it into the ones that can lumped together - if one piece of code can handle all "apostrophes", then it's a good fit for one issue. If another tokenizer library solves N languages, this would cover them. Otherwise we'll be lost in the trap of "there's still so many languages left".

Also, isn't chinese already solved with Jieba?

**Comment by ftyers** [comment]
@d33tah yeah, it's solved, but it would still be good to have a test case for it. Most of the apostrophe cases are language dependent. But don't worry I'm familiar with most of these so we won't get lost.

**Comment by ftyers** [comment]
Note that we don't actually have to make a perfect tokeniser, we just have to deal with the punctuation that is in the Common Voice files. I've basically just been doing:
```bash
cat ~/source/common-voice/server/data/as/* | grep '\W' 
```
and then adding the most frequent stuff. This is also a useful command:

```bash
$ cat ~/source/common-voice/server/data/as/* | grep -o '\W' | sort -u | tr -d '\n' 
!"',-.:;?°।৷৹‘’“”
```

**Comment by ftyers** [comment]
I'm going to close this issue now, after adding Punjabi in bd5ae49. Any issues with tokenisers should now be filed as separate issues.
