### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by d33tah** [omnilingo/omnilingo#71]
It can be as simple as a paragraph explaining the project and inviting to try out the demo.

**Comment by ftyers** [comment]
I've started it: https://github.com/omnilingo/omnilingo.github.io/

**Comment by ftyers** [comment]
It now looks up the languages and when you click takes you to the page?

**Comment by ftyers** [comment]
Ok, this is done, I've added some copy, we can always change it later.
