### ISSUE TITLE
Create a tokeniser for Italian

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#84]
The Italian corpus has a lot of non-alphabetic characters in it:

```
$ cat ~/source/common-voice/server/data/it/* | grep -o "\W" | sort -u | tr -d '\n'
੝­​﻿!"#%&'()+,-./:;<=>?[]`{|}~¡«¬®°´·»¿΄״‐‑‒–—―‘’‛“”„†…′″‹›←→↵−≡☆♡♭♯⟨⟩。・，￼़̨̩̣̥̱̓́̀͡  $£€्્
```

This probably requires a bit of a different approach, e.g. stripping some of the characters, or filtering some of the sentences.

**Comment by d33tah** [comment]
Do you get the same output when only looking at validated.tsv? I'm only getting `!"#$'()+,-./:;<=>?[]`~¡«°´»–‘’“”„…`.

**Comment by ftyers** [comment]
I was actually looking at the whole common voice corpus from sentence collector, so in principle we could just use the punctuation in this release.
