### ISSUE TITLE
mobile stylesheet

### ISSUE THREAD

**Issue by jonorthwash** [omnilingo/omnilingo#91]
Currently on mobile devices it has ridiculous margins and is tiny inside those margins.

**Comment by ftyers** [comment]
So, i've added `viewport` and that helps with the height/zoom issue, I'm not sure what else can be done aside from making a specific mobile layout, which is beyond my ken.

**Comment by ftyers** [comment]
This is now kind of / mostly fixed? The player is still a bit off, but it's reasonably functional on mobile now.
