### ISSUE TITLE
Add drag-and-drop functionality for touch screens

### ISSUE THREAD

**Issue by jonorthwash** [omnilingo/omnilingo#92]
Drag-and-drop is currently non-functional on touch-screen devices.

**Comment by ftyers** [comment]
So, this is [difficult](https://stackoverflow.com/questions/3382393/html5-drag-and-drop-api-on-touch-screen-devices) we'll probably need a different interface for touch devices, or change the desktop interface, e.g. click to select/copy, click to paste/drop.

**Comment by jonorthwash** [comment]
>  for touch devices, or change the desktop interface, 

Touch-screen devices and desktop platforms are not mutually exclusive...  The two devices with desktop OSes that I use the most both have touch screens.

**Comment by ftyers** [comment]
I've updated it so that it now uses clicks instead of drag and drop. This seems to work on mobile too.
